### ISSUE TITLE
module 'Houseweb.views' has no attribute 'tf_train'

### ISSUE THREAD

**Issue by Mistrymm7** [HanHan55/Graph2plan#12]
![image](https://user-images.githubusercontent.com/7644450/111634019-16281f00-87c4-11eb-9511-b8d44b4e69e3.png)

**Comment by HanHan55** [comment]
Since you provided too little information, I can only guess that it might be a data problem.
1.Provide more information to solve it together.
2.Your operation is too fast, and the data has not been loaded successfully so that an error is reported.
3.Did you download the data from the website (http://vcc.tech/file/upload_file/Data/G2P/Data.7z)? And Place the unzipped data in a folder with the same file name as the project code.Maybe you don't put the file "tf_train.npy" under the folder "retrieval".
